#!/bin/bash
g++ ./blt.cpp -o ./blt
rm ./blt.cpp

g++ ./bs.cpp -o ./bs
rm ./bs.cpp

g++ ./fade.cpp -o ./fade
rm ./fade.cpp

g++ ./touchInput.cpp -o ./touchInput
rm ./touchInput.cpp

g++ ./touchInputLogger.cpp -o ./touchInputLogger
rm ./touchInputLogger.cpp

rm -rf ./.vscode
rm -rf ./.git
rm ./.gitignore
rm ./.gitattributes

sudo mv ./SleepMode.service /etc/systemd/system/SleepMode.service
sudo systemctl enable SleepMode.service
sudo systemctl start SleepMode.service

echo "#!/bin/bash
sudo systemctl disable SleepMode.service
sudo systemctl stop SleepMode.service
sudo rm /etc/systemd/system/SleepMode.service
cd ..
sudo rm -rf ./piBackLight
" > ./uninstall
chmod +x ./uninstall
rm ./install
