#!/bin/bash
g++ ${PWD}/blt.cpp -o ${PWD}/blt
rm ${PWD}/blt.cpp

g++ ${PWD}/bs.cpp -o ${PWD}/bs
rm ${PWD}/bs.cpp

g++ ${PWD}/fade.cpp -o ${PWD}/fade
rm ${PWD}/fade.cpp

g++ ${PWD}/touchInput.cpp -o ${PWD}/touchInput
rm ${PWD}/touchInput.cpp

g++ ${PWD}/touchInputLogger.cpp -o ${PWD}/touchInputLogger
rm ${PWD}/touchInputLogger.cpp

rm -rf ${PWD}/.vscode
rm -rf ${PWD}/.git
rm ${PWD}/.gitignore
rm ${PWD}/.gitattributes

sudo systemctl disable SleepMode.service
sudo systemctl stop SleepMode.service
sudo rm /etc/systemd/system/SleepMode.service
sudo mv ${PWD}/SleepMode.service /etc/systemd/system/SleepMode.service
sudo systemctl enable SleepMode.service
sudo systemctl start SleepMode.service
export PATH="${PWD}:$PATH"

echo "#!/bin/bash
sudo systemctl disable SleepMode.service
sudo systemctl stop SleepMode.service
sudo rm /etc/systemd/system/SleepMode.service
oldDir=\${PWD}
cd ..
sudo rm -rf \$oldDir
" > ./uninstallPiBackLight
chmod +x ./uninstallPiBackLight
rm ./install
